vtd_lidar:
  ros__parameters:
    use_sim_time: true

    lidar_udp:
      bind_address: 0.0.0.0
      port: 9912
      socket_receive_buffer_bytes: 4194304

    map_frame: map
    lidar_frame: lidar_link
    map_offset:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0

    topics:
      pointcloud: /sensing/lidar/concatenated/pointcloud
